### ISSUE TITLE
AzureReader2 on nightlies throwing NRE

### ISSUE THREAD

**Issue by danielcrenna** [imazen/resizer#144]
Using Ben Foster's simple walkthrough, on nightlies, new project, verified blob, nuget is up to date.

Link to repro: https://www.dropbox.com/s/csbowsp9es2zoi7/image.svc.zip?dl=0

Note that I have no queryString parameters and am expecting a redirect or proxy to Azure depending on default, but this happens instead.

at System.String.StartsWith(String value, StringComparison comparisonType)
at ImageResizer.Storage.BlobProviderBase.Belongs(String virtualPath) in c:\projects\resizer\Plugins\ImageResizer.Storage\BlobProviderBase.cs:line 135
at ImageResizer.Storage.BlobProviderBase.FileExists(String virtualPath, NameValueCollection queryString) in c:\projects\resizer\Plugins\ImageResizer.Storage\BlobProviderBase.cs:line 206
   at ImageResizer.Configuration.PipelineConfig.GetFile(String virtualPath, NameValueCollection queryString)
   at ImageResizer.InterceptModule.CheckRequest_PostAuthorizeRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

URL in a completely empty Web Application is:
`http://localhost:8080/azure/test/test.jpg`

(where `test` is the container and `test.jpg` is the name of the blob)

This is my config:

`<add name="AzureReader2" connectionString="DefaultEndpointsProtocol=https;AccountName=[FOO];AccountKey=[BAR]"
endpoint="http://[FOO].blob.core.windows.net/" />`

**Comment by lilith** [comment]
Does adding `prefix="~/azure"` avoid the error? If so, https://github.com/imazen/resizer/commit/fd6eb0fa8fc05da8215af14a0ddd7a6a05fd41ce should resolve the problem.

**Comment by danielcrenna** [comment]
Actually the opposite. Adding a prefix of any kind forces a 404 error not a blob provider base error. I have to remove the prefix to get the plugin to attempt an Azure resolution and that's even if I make it the same as the default. Had a feeling trailing slashes were significant in this part of the code but could be wrong.

**Comment by lilith** [comment]
So the redirection occurs? Add `vpp="true"`, since older builds don't have that default.

**Comment by danielcrenna** [comment]
Will do and if not I'll dig in further, but I'm on the nightlies.

**Comment by lilith** [comment]
A new nightly should be out.

**Comment by danielcrenna** [comment]
Looks good. It would be nice if the redirect worked with private files, but this bug is solved due to the helpful defaults.
