### ISSUE TITLE
Imageresizer GDI+

### ISSUE THREAD

**Issue by PatelNimit** [imazen/resizer#153]
image resizer throwing error for GDI+,

```
Exception information: 
    Exception type: ExternalException 
    Exception message: A generic error occurred in GDI+.
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at ImageResizer.ImageBuilder.buildToStream(Bitmap source, Stream dest, ResizeSettings settings)
   at ImageResizer.ImageBuilder.BuildJob(ImageJob job)
   at ImageResizer.ImageBuilder.Build(ImageJob job)
   at ImageResizer.ImageBuilder.Build(Object source, Object dest, ResizeSettings settings, Boolean disposeSource, Boolean addFileExtension)
   at ImageResizer.ImageBuilder.Build(Object source, Object dest, ResizeSettings settings, Boolean disposeSource)
   at ImageResizer.ImageBuilder.Build(Object source, Object dest, ResizeSettings settings)
   at ImageResizer.InterceptModule.<>c__DisplayClass3.<HandleRequest>b__2(Stream stream)
   at ImageResizer.Plugins.DiskCache.CustomDiskCache.<>c__DisplayClass5.<GetCachedFile>b__0()
   at ImageResizer.Plugins.DiskCache.LockProvider.TryExecute(String key, Int32 timeoutMs, LockCallback success)
   at ImageResizer.Plugins.DiskCache.CustomDiskCache.GetCachedFile(String keyBasis, String extension, ResizeImageDelegate writeCallback, DateTime sourceModifiedUtc, Int32 timeoutMs, Boolean asynchronous)
   at ImageResizer.Plugins.DiskCache.DiskCache.Process(IResponseArgs e)
   at ImageResizer.Plugins.DiskCache.DiskCache.Process(HttpContext context, IResponseArgs e)
   at ImageResizer.InterceptModule.HandleRequest(HttpContext context, String virtualPath, NameValueCollection queryString, IVirtualFile vf)
   at ImageResizer.InterceptModule.CheckRequest_PostAuthorizeRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

```

Can any one help to resolve this critical issue?

Thanks,
Nimit

**Comment by lilith** [comment]
Please provide more information [as per our support guidelines](http://imageresizing.net/support): 
- The diagnostics page - so we know what version of ImageResizer you're using and your environment details.
- Precise steps to reproduce the issue.

**Comment by PatelNimit** [comment]
Thanks Jones for your urgent reply.

Getting GDI+ error periodically as it is not constant. Once we recycle App pool image resizer is working fine once again. After certain time same issue found again.

Following is image tag in html
&lt;img alt="Image" src="https://domain.com:443/front.png?trim.threshold=80&trim.percentpadding=0.5&width=1000"&gt;

When I have tried image url directly in address bar getting following generic error message.

`The image “https://domain.com:443/front.png?trim.threshold=80&trim.percentpadding=0.5&width=1000" cannot be displayed because it contains errors.`

Here is the diagnosis result of page.

```
Image resizer diagnostic sheet      9/11/2015 8:59:10 PM

0 Issues detected:


You are using plugins from the Creative Edition: DiskCache (Performance Edition), WhitespaceTrimmerPlugin (Creative Edition)

Registered plugins:

ImageResizer.Plugins.Basic.DefaultEncoder
ImageResizer.Plugins.Basic.NoCache
ImageResizer.Plugins.Basic.ClientCache
ImageResizer.Plugins.Basic.Diagnostic
ImageResizer.Plugins.Basic.SizeLimiting
ImageResizer.Plugins.DiskCache.DiskCache
ImageResizer.Plugins.WhitespaceTrimmer.WhitespaceTrimmerPlugin

Configuration:

<resizer>
<pipeline fakeExtensions=".ashx" />
<plugins>
<add name="DiskCache" />
<add name="WhitespaceTrimmer" />
</plugins>
<sizelimits imageWidth="0" imageHeight="0" totalWidth="4000" totalHeight="4000" totalBehavior="throwexception" />
<diskCache dir="~/imagecache" autoClean="true" hashModifiedDate="true" enabled="true" subfolders="8192" cacheAccessTimeout="15000" asyncWrites="true" asyncBufferSize="10485760" />
<cleanupStrategy startupDelay="00:05" minDelay="00:00:20" maxDelay="00:05" optimalWorkSegmentLength="00:00:04" targetItemsPerFolder="400" maximumItemsPerFolder="1000" avoidRemovalIfCreatedWithin="24:00" avoidRemovalIfUsedWithin="4.00:00" prohibitRemovalIfUsedWithin="00:05" prohibitRemovalIfCreatedWithin="00:10" />
</resizer>


Accepted querystring keys:

quality, format, thumbnail, trim.percentpadding, trim.threshold, maxwidth, maxheight, width, height, w, h, scale, stretch, crop, cropxunits, cropyunits, page, bgcolor, rotate, flip, sourceFlip, sFlip, sRotate, borderWidth, borderColor, paddingWidth, paddingColor, ignoreicc, frame, useresizingpipeline, cache, process, margin, anchor, dpi, mode, zoom, 

Accepted file extensions:

bmp, gif, exif, png, tif, tiff, tff, jpg, jpeg, jpe, jif, jfif, jfi, 

Environment information:

Running Microsoft-IIS/7.5 on Microsoft Windows NT 6.1.7601 Service Pack 1 and CLR 4.0.30319.34209
Trust level: Unrestricted
OS bitness: AMD64
Executing assembly: c:\windows\system32\inetsrv\w3wp.exe
IntegratedPipeline: True

Loaded assemblies:

mscorlib                                 Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Web                               Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System                                   Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Core                              Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Web.ApplicationServices           Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Configuration                     Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Xml                               Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
Microsoft.Build.Utilities.v4.0           Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Runtime.Caching                   Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
Microsoft.JScript                        Assembly: 10.0.0.0        File: 12.0.51209.34209 Info: 12.0.51209.34209
System.ServiceModel.Activation           Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Web.Extensions                    Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
Microsoft.CSharp                         Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Data                              Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Web.Services                      Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Drawing                           Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.EnterpriseServices                Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.IdentityModel                     Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Runtime.Serialization             Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.ServiceModel                      Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.ServiceModel.Web                  Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Activities                        Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.ServiceModel.Activities           Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.WorkflowServices                  Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Data.DataSetExtensions            Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Xml.Linq                          Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.ComponentModel.DataAnnotations    Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Web.DynamicData                   Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
AForge                                   Assembly: 2.2.4.0         File: 2.2.4.0        
AForge.Imaging                           Assembly: 2.2.4.0         File: 2.2.4.0        
AForge.Math                              Assembly: 2.2.4.0         File: 2.2.4.0        
ImageResizer                             Assembly: 3.4.3.103       File: 3.4.3.103       Info: 3-4-3  Commit: bf92fd7
ImageResizer.Plugins.DiskCache           Assembly: 3.4.3.103       File: 3.4.3.103       Info: 3-4-3  Commit: bf92fd7
ImageResizer.Plugins.WhitespaceTrimmer   Assembly: 3.4.3.103       File: 3.4.3.103       Info: 3-4-3  Commit: bf92fd7
System.ServiceModel.Internals            Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Web.Mobile                        Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Web.RegularExpressions            Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
SMDiagnostics                            Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
System.Xaml.Hosting                      Assembly: 4.0.0.0         File: 4.0.30319.34209 Info: 4.0.30319.34209
```

**Comment by nathanaeljones** [comment]
Steps to reproduce?

**Comment by PatelNimit** [comment]
Getting GDI+ error periodically as it is not constant. Once we recycle App pool image resizer is working fine once again. After certain time same issue found again.

Following is image tag in html
&lt;img alt="Image" src="https://domain.com:443/front.png?trim.threshold=80&trim.percentpadding=0.5&width=1000"&gt;

When I have tried image url directly in address bar getting following generic error message.

`The image “https://domain.com:443/front.png?trim.threshold=80&trim.percentpadding=0.5&width=1000" cannot be displayed because it contains errors.`

**Comment by lilith** [comment]
So after this error first occurs, do _any_ image requests succeed? Is there any other source code running in this application pool? What does memory usage look like when failures start occurring?

**Comment by PatelNimit** [comment]
@nathanaeljones : Yes, same application pool is used for application code. memory usage is normal before and after issue occur.

**Comment by lilith** [comment]
You need to put them into separate application pools for diagnosis. This problem usually occurs when external app code puts GDI into an invalid state.

If your app is open-source, I can review the source code. Otherwise this may be difficult to troubleshoot without a support contract.

**Comment by lilith** [comment]
Closing as no response received; cannot reproduce.
