### ISSUE TITLE
Exceptions when attempting to serve files with colons in the name

### ISSUE THREAD

**Issue by sixten** [imazen/resizer#179]
We're seeing quite a few exceptions thrown by the image server that appear to result from files with colons in their names. We're pulling them down from S3 (which has quite permissive naming rules for files), but it's not clear at what point exactly in the image processing the failure is happening. I'm guessing it's at some point in the process of writing the file to disk in the disk caching. (Many, many other requests for other images work just fine.)

I suspect this is not strictly limited to colons, but would include any other characters or substrings that this canonicalization process considers problematic.

Here's the exception:

```
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath)
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.Web.Hosting.HostingEnvironment.MapPath(VirtualPath virtualPath)
   at ImageResizer.Configuration.HttpModuleRequestAssistant.PostAuthorize()
   at ImageResizer.InterceptModule.CheckRequest_PostAuthorizeRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by lilith** [comment]
It's not related to disk caching at all, but rather security authorization. 

While S3 doesn't use filenames, and can accept arbitrary keys, ASP.NET requires that paths be valid filenames. 

We support ASP.NET URL authorization, but to support it we must use MapPath. MapPath requires paths be valid filenames. 

If these are public images, you might try RemoteReader (it doesn't support invalidation, but can trigger arbitrary HTTP requests if you use the signed syntax with a key).

**Comment by sixten** [comment]
I don't understand: why is there a path or URL that includes the S3 key? What exactly is being authorized?

If nothing else, it would be good to document this requirement for `S3Reader2` that keys must conform to Windows file naming constraints.

**Comment by lilith** [comment]
S3 blobs are accessed by container and key (the blob identifier). 

ASP.NET has a URL Authorization system. Even if _you_ aren't using it, we have to ensure that our HttpModule doesn't introduce a way to circumvent it. 

If you like, blame this on ASP.NET's infamous PathInfo handling. Even if we didn't use MapPath ourselves, you would likely see failure later on. S3 blob identifiers will always be a superset of what IIS and ASP.NET permit in URLs before the querystring.
