### ISSUE TITLE
No image encoder was found for the request

### ISSUE THREAD

**Issue by chicky994** [imazen/resizer#452]
Hi team,

Our customer is having an issue with ImageResizer.
The error:
`EPiServer.Global : Unhandled exception in ASP.NET
ImageResizer.ImageProcessingException (0x80004005): Image Resizer: No image encoder was found for the request.
   at ImageResizer.Configuration.HttpModuleRequestAssistant.EstimateResponseInfo()
   at ImageResizer.InterceptModule.HandleRequest(HttpContext context, HttpModuleRequestAssistant ra, IVirtualFile vf)
   at ImageResizer.InterceptModule.CheckRequest_PostAuthorizeRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.<>c__DisplayClass285_0.<ExecuteStepImpl>b__0()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`

Could you please help us to see what could be causing this problem?

Thanks,

**Comment by lilith** [comment]
Hi! Can you access /resizer.debug to get the version & config? Also, what
was the url and querystring this is happening on?

**Comment by chicky994** [comment]
Hi Lilith,

They are using the versions below:
ImageResizere.Core: 4.0.1
ImageResizere.Plugins.EpiFocalPoint: 2.0.1
ImageResizer.Plugins.EPiServerBlobReader: 7.2.1.0

I'm not sure how to find the resizer.debug to get the config.
Attached a capture request failed on Application Insight.
![ImageResizer](https://user-images.githubusercontent.com/102512763/203941749-020eab8f-b815-48c8-a861-a1d342f33f39.PNG)

Please let me know if you need further information.

Thanks,

**Comment by lilith** [comment]
Please upgrade to 4.2.8, that version is over 5 years old.

**Comment by chicky994** [comment]
Hi Lilith,

Thank you for suggestion.
I will let our customer know this.

Hope this helps.
